Updated to use upring plugin system
mcollina/upring-kv pull request #1
Opened 2017-11-22 09:53 UTC by delvedor

As titled.

The `bin` component has been removed since is not useful anymore.
Also added *async-await* support.

2017-11-22 16:57 UTC, lucamaraschi approved these changes

2017-12-06 10:41 UTC, mcollina commented
I think the `bin` component is still __very__ useful for testing and demos. Can you please restore it?

2017-12-06 10:41 UTC, mcollina commented on package.json
> +    "upring": "^0.21.0"
We have upring 0.22.0 now"

2017-12-06 10:42 UTC, mcollina requested changes
I think the `bin` component is still __very__ useful for testing and demos. Can you please restore it?

2017-12-06 14:50 UTC, delvedor commented
@mcollina instead of restoring it, why not build a separate package just for this purpose?

2017-12-06 15:00 UTC, mcollina commented
That’s also ok, can you add it to the org?

2017-12-06 15:20 UTC, delvedor commented
Sure!
Let's merge and release this, then I'll work on the new package :)

2017-12-06 15:55 UTC, delvedor commented
https://github.com/upringjs/kv-demo

2017-12-06 16:03 UTC, mcollina approved these changes
LGTM

2017-12-06 18:08 UTC, merged